```{r libraries, echo = FALSE, message = FALSE}
library(dplyr)
library(tidyr)
library(intervals)
library(stringr)
library(purrr)
library(tibble)  # for `rownames_to_column` and `column_to_rownames`
library(rlist)
```

```{r data.loading, echo = FALSE}
ranges <-
    pipe("perl < 16-input -ne '
     BEGIN { print join(q(,), qw(field from1 to1 from2 to2)), qq(\\n) };
     exit unless my @fields = m/(.*?): (\\d+)-(\\d+) or (\\d+)-(\\d+)/;
     print join(q(,), @fields), qq(\\n)'") %>%
    read.csv(header = TRUE) %>%
    tibble

tickets <- pipe("perl < 16-input -ne 'BEGIN { $_ = <> until m/nearby tickets/; } print'") %>%
    read.csv(header = FALSE) %>%
    tibble

your.ticket <- pipe("perl < 16-input -e 'do { $_ = <> } until m/your ticket:/; print(scalar <>)'") %>%
    read.csv(header = FALSE)

```

# First question

Estimate rate of false tickets (those that have at
least one completely aberrant number)

```{r q1, echo = FALSE, message = FALSE}
intervals_Z <- function(from_v, to_v) {
    Intervals_full(c(from_v, to_v), type = "Z") %>%
        intervals::reduce()
}

allowed.values <- interval_union(c(
    intervals_Z(ranges$from1, ranges$to1),
    intervals_Z(ranges$from2, ranges$to2)))

if (! exists("%within%")) {
    `%within%` <- function (a, b) standardGeneric("%within%")
}

setMethod("%within%", c(a = "numeric", b = "Intervals_full"),
          function(a, b) {  ## Vectorized over a *only*

              ## https://stackoverflow.com/a/7660073/435004
              inwhich <- function(indices, .length)
                  is.element(seq_len(.length), indices)

              Intervals_full(c(a, a), type = "Z") %>%
                  interval_included(from = b) %>%
                  c %>% inwhich(length(a))
          })

stopifnot(identical(
    c(TRUE, TRUE, FALSE),
    c(1, 0, 3) %within% intervals_Z(0, 2)))

bogons <-
    tickets %>%
    mutate(across(everything(),
                  ~ ifelse(.x %within% allowed.values, NA, .x))) %>%
    pivot_longer(everything()) %>%
    filter(! is.na(value))
```

The “ticket scanning error rate” (which is actually not an error rate
at all), is `r bogons$value %>% sum`

```{r guess.mapping, echo = FALSE}

good.tickets <-
    tickets %>%
    filter(across(everything(), ~ .x %within% allowed.values))

plausible <- ranges %>%
    mutate(summarize(
        good.tickets,
        across(everything(), function(tickets.column) {
            all.within.bounds <- function(numbers_v, from1, to1, from2, to2) {
                all((numbers_v >= from1 & numbers_v <= to1) |
                    (numbers_v >= from2 & numbers_v <= to2))
            }
            pmap_lgl(.,  function(field, from1, to1, from2, to2)
                all.within.bounds(tickets.column, from1, to1, from2, to2))
        }))) %>%
    select(-c(from1, from2, to1, to2)) %>%
    tibble::column_to_rownames("field")

assume <- function(plausible, x, y) {
    stopifnot(plausible[x, y])
    plausible <- rlang::duplicate(plausible)
    for(x1 in rownames(plausible)) plausible[x1, y] <- x1 == x
    for(y1 in colnames(plausible)) plausible[x, y1] <- y1 == y
    plausible
}

solve <- function(plausible) {
    solutions <- list()
    solve.recursive <- function(plausible, settled.rows, settled.cols) {
        # print("_ plausible:")
        # print(plausible)
        # print("_ settled.rows:")
        # print(settled.rows)
        # print("_ settled.cols:")
        # print(settled.cols)

        cols <-
            plausible %>%
            summarize(across(everything(), ~ length(which(.)))) %>%
            pivot_longer(everything(),
                         names_to = "column",
                         values_to = "total") %>%
            arrange(total)
        rows <-
            plausible %>%
            rownames_to_column("row") %>%
            rowwise() %>%
            transmute(row = row,
                      total = rowSums(across(-row))) %>%
            ungroup() %>%
            arrange(total)

        if (rows %>% filter(total == 0) %>% nrow) {
            ## This is not a solution; do nothing
        } else if (cols %>% filter(total == 0) %>% nrow) {
            ## Ditto
        } else if ( (!(rows %>% filter(total != 1) %>% nrow)) &&
                    (!(cols %>% filter(total != 1) %>% nrow)) ) {
            ## The matrix is now a permutation, i.e. it is a solution.
            solution <- plausible %>%
                rownames_to_column("field") %>%
                pivot_longer(-field) %>%
                filter(value == TRUE) %>%
                transmute(field = field, column = name)
            solutions <<- list.append(solutions, solution)
        } else {
            ## Walk moar
            best.row <-
                rows %>%
                filter(! row %in% settled.rows) %>%
                slice(1) %>%
                pull(row)

            if (! identical(character(0), best.row)) {
                for(col in cols %>%
                           filter(! column %in% settled.cols) %>%
                           pull(column)) {
                    if (plausible[best.row, col]) {
                        # print(sprintf("* plausible[%s, %s]", best.row, col))

                        solve.recursive(
                            assume(plausible, best.row, col),
                            c(settled.rows, best.row),
                            c(settled.cols, col))
                    }
                }
            }
        }
    }

    solve.recursive(plausible, c(), c())
    solutions
}

column.mapping <<- solve(plausible)[[1]]

your.ticket.decoded <- your.ticket %>%
    pivot_longer(everything(), names_to = "column") %>%
    left_join(column.mapping, by = "column") %>%
    select(-column)
```

# Your ticket (decoded)

```{r your.ticket.decoded}
your.ticket.decoded %>% as.data.frame
```
